sudo: required
dist: trusty
language: node_js
node_js:
  - node

services:
  - mongodb

mongodb:
  adapter: mongodb
  database: billvoting
  username: merdoth
  
before_script:
  - npm install
  - sleep 15

script:
  - npm run test

after_success:
  - npm run coveralls
