language: node_js
node_js:
  - "node"
  - "6.11.2"
before_install:
  - npm install
  - sleep 15
script:
  - npm run test
after_script:
  - npm run coverage

services: mongodb

env:
  CODECLIMATE_REPO_TOKEN: 713671664457aabeba4337bdb71661e72c73414ad1f15d397c5ee43ed8087ae1
